# -*- coding: utf-8 -*-
"""Week 4_Session1_me.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gz-AFe77Sb0eh3ldwtSY4IMNJONpU9SQ
"""

n1 = int(input("Enter the first number: "))
n2 = int(input("Enter the second number: "))
opr = input("Enter the operator: ")

match opr:
    case '+':
        print(f"{n1} + {n2} = {n1 + n2}")
    case '-':
        print(f"{n1} - {n2} = {n1 - n2}")
    case '*':
        print(f"{n1} * {n2} = {n1 * n2}")
    case '/':
        print(f"{n1} / {n2} = {n1 / n2}")
    case '%':
        print(f"{n1} % {n2} = {n1 % n2}")
    case _:
        print("Invalid operator")

num = 123
sum = 0

while num>0  :
  digit = num % 10
  sum += digit
  num //= 10

print(f"Sum of digits: {sum}")

num = int(input("Enter a number: "))
lst = []

while num>0:
  digit = num % 10
  lst.append(digit)
  num //= 10

for digit in lst:
  print(digit, end = "")

num = int(input("Enter a number: "))
lst = []

while num>0:
  digit = num % 10
  lst.append(digit)
  num //= 10

print("The reversed num is: ", end = "")
for digit in lst:
  print(digit, end = "")

original_num = int(input("Enter a number to reverse: "))
num = original_num
reversed_num = 0

while num > 0:
  digit = num % 10
  reversed_num = reversed_num * 10 + digit
  num //= 10

print(f"The reversed number is: {reversed_num}")

original_num = int(input("Enter a number: "))
n = original_num
reversed_num = 0

while n > 0:
  digit = n % 10
  reversed_num = reversed_num * 10 + digit
  n //= 10

if original_num == reversed_num:
  print(f"{original_num} is a palindrome number.")
else:
  print(f"{original_num} is not a palindrome number.")

original_num = int(input("Enter a number: "))
n = original_num
reversed = []

while n > 0:
  digit = n % 10
  reversed.append(digit)
  n //= 10

reconstructed_reversed_num = 0
for digit in reversed:
  reconstructed_reversed_num = reconstructed_reversed_num * 10 + digit

if original_num == reconstructed_reversed_num:
  print(f"{original_num} is a palindrome number.")
else:
  print(f"{original_num} is not a palindrome number.")

"""# Binary Converter"""



"""# Armstrong Number"""

num = 153