# -*- coding: utf-8 -*-
"""Practice_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdoKpxLX81_I84j--23g58uVPNiObyh-

Questions on Your Notebook
🔹 Part 1: Basic Print

Write a program that prints your full name.

Print your faculty and your university in one line.

Print your age in a separate line.
"""

name=input()
faculty_name=input()
age=int(input())
print(f"name is {name} Faculty is {faculty_name}")
print(age)



"""Part 2: Quotes Practice

Print the following sentence correctly:

I'm learning Python


Print this sentence without error:

He said "Python is easy"


What is the difference between:

print("hello")

print('hello')
"""

print("I'am learning pythonz")

print('I\'am learning python')

print("\"python is easy\"")

"""Part 3: Multiple Values in Print

Write one print statement that prints:

AI Data Science 2026


(in one line using commas)

Rewrite the previous question but print each word in a separate line.
"""

s="AI Data Science 2026"
print("AI","Data","Science","2026",sep='Nour',end='***')
print("Ahmed")

print("Caren","2026",sep="***")
print("QQQQ",end="*****")
print("Faries")

"""Part 5: Challenge ✨

Print this exactly as shown:

```

Hello
    AI
        World


```  
"""

print("Hello\n  AI\n    Word")

print("Hello\n\tAI\n\t\tword")

print("Hello"," AI","   word",sep='\n\t')

"""Print this sentence using only ONE print statement:

Today is 29-12-2025

I am learning Python

"""

print("Today is 29-12-2025\n\nI am learning Python")

print("Today is 29-12-2025","I am learning Python",sep='\n\n')



"""Level Up – Variables + Operators + Logic
🔹 Part 1: Variables

Create two variables:

x = 10

y = 5

Then print their:

Sum

Difference

Multiplication

Division
"""

x=1000
y=3

sum=x+y
dif=x-y
mult=x*y
div=x/y
poww=x**y
print(f"sum = {sum} difference = {dif} multy = {mult} div={div:.3f}")



"""What is wrong here?

1num = 5
"""





"""Part 2: Operators

What is the result?

print(10 // 3)

print(10 % 3)
"""

print(10//3)

print(10%3)

"""What is the difference between:

10 / 2

10 // 2
"""

print(type(5/2))

print(type(5//2))

"""Part 3: Logic (Comparison Operators)

What is the output?

print(5 > 3)

print(5 == 3)

print(5 != 3)

"""

print(5>3)

print(3==3)

print(5!=5)

"""Given a name S. Print "Hello, (name)" without parentheses.

Input
Only one line containing a string S.

Output
Print "Hello, " without quotes, then print name.

Example

Input

programmer

Output

Hello, programmer
"""

name=input()
print(f"Hello, {name}")





"""Given two numbers X and Y. Print the summation and multiplication and subtraction of these 2 numbers.

Input

Only one line containing two separated numbers X, Y (1  ≤  X, Y  ≤  105).

Output

Print 3 lines that contain the following in the same order:

"X + Y = summation result" without quotes.

"X * Y = multiplication result" without quotes.

"X - Y = subtraction result" without quotes.

Example

Input

5 10

Output

5 + 10 = 15

5 * 10 = 50

5 - 10 = -5

Note

Be careful with spaces.
"""

x=int(input())
y=int(input())
print(f"{x} + {y} = {x+y}")
print(f"{x} * {y} = {x*y}")
print(f"{x} - {y} = {x-y}")





"""Given four numbers A, B, C and D. Print the result of the following equation :

 X = (A * B) - (C * D).

Input

Only one line containing 4 separated numbers A, B, C and D ( - 105  ≤  A, B, C, D  ≤  105).

Output

Print "Difference  =  " without quotes followed by the equation result.

Examples

Input

1 2 3 4

Output

Difference = -10

Input

2 3 4 5

Output

Difference = -14

Input

4 5 2 3


Output

Difference = 14


"""

a=int(input());b=int(input());c=int(input());d=int(input())
print(f"Difference =  {(a*b)-(c*d)}")



"""Given a number R calculate the area of a circle using the following formula:

Area = π * R^2.

Note: consider π = 3.141592653.

Input

Only one line containing the number R (1  ≤  R  ≤  100).

Output

Print the calculated area, with 9 digits after the decimal point.

Example

Input

2.00

Output

12.566370612
"""

p=3.141592653
r=float(input())
area=p*r**2
print(f"{area:.9f}")

import math
p=math.pi
print(p)

"""Given two numbers N and M. Print the summation of their last digits.

Input

Only one line containing two numbers N, M (0 ≤ N, M ≤ 1018).

Output

Print the answer of the problem.

Example

Input

13 12

Output

5
"""

#26 21 >>7

x=int(input())
y=int(input())
print((x%10)+(y%10))

"""Given a number N

. Print the summation of the numbers that is between 1 and N
 (inclusive).

Input

Only one line containing a number N
 (1≤N≤109)

Output

Print the summation of the numbers that are between 1 and N
 (inclusive).

Examples

Input

3

Output

6

Input

10

Output

55
"""

n=int(input())
sum=(n*(n+1))//2
print(sum)

print(type(20//5))

