# -*- coding: utf-8 -*-
"""2nd.Session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjmp8co3tajdRTlv8mkpt0xNPxNuCHCK
"""


s = input("Enter Ur Sentence: ")
print(f"First Character: {s[0]}")
print(f"Last Character: {s[-1]}")



s = input("Enter Ur Word: ")
print(f"length of the word: {len(s)}")



s = input("Enter Ur Text: ")
print(f"uppercase: {s.upper()}")
print(f"lowercase: {s.lower()}")
print(f"length of the text: {len(s)}")
print(f"number of words: {len(s.split())}")



s = input("Enter Ur Text: ")
s = s[::-1]
print(f"Reversed Text: {s}")






