# -*- coding: utf-8 -*-
"""2nd.Session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjmp8co3tajdRTlv8mkpt0xNPxNuCHCK
"""



# Split
sentence = "Python is a programming language"
print(sentence.split())

sentence = "name,age,country"
print(sentence.split(","))

sentence ="Hello***World***Python"
print(sentence.split("***"))

# Replace
s = "Hello World, Hello World"
print(s.replace("World", "Python"))
print(s.replace("World", "Python", 1))

# Join
words = ["Hello", "From", "the", "AI", "Course"]

print(" ".join(words))
print("_".join(words))

# f-string
score = 87
print(f"Your Score is {score} out of 100")

name  = "Ali"
age = 19
print(f"My name is {name.upper()} and I am {age} years old")

# Cse Conversion
s = "Hello World"
print(s.upper())
print(s.lower())
print(s.capitalize())

# String Operations
print(len(s))
print(max(s))
print(min(s))
print(s * 4)
print(s + "     "  + s)

# Indexing
s = "ABCD"
print(s[0], s[1], s[2], s[3], s[-1], s[-2], s[-3], s[-4])
print(s.index("A"))
print(s.find("B"))

# Slicing  :: s[start:stop:step]  Default: Start=0 , step=1
s = "ABCDEFG"
print(s[3:6])
print(s[3:6:1])
print(s[0:6:2])
print(s[::])   # = s[0:len(s):1]
print(s[1::])
print(s[::1])
print(s[-1::])
print(s[::-1])
print(s[6:0:-2])

s = s[::] + "H"
print(s)

# Stings are Immutable
s = "Hello"
s = 'y' + s[1:len(s)]
print(s)

hi = "Hello There"
name = "Ali"
greeting = hi + " " + name
greet = hi , name # Tuple

print(greeting)
print(name*3)
print(hi + " " + name*3)
print(hi, name)
print(greet)   # Tuple
print(greet*3)
print(type(greet))