# -*- coding: utf-8 -*-
"""Week3_Session2_me.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhLorzrfBS23jTQQkbluBTDqLW6guQ3h
"""

n = int(input("Enter a number: "))
rows = n
col = (n*2)-1
for i in range(rows):
  for j in range(col):
    if i == 0 or i == rows-1 or j == 0 or j == col-1 or j == int(col/2):
      print("*", end="")
    else:
      print(" ", end="")

  print("")

rows = 4
columns = 10
for i in range(rows):
  for j in range(columns):
    if i == 0 or i == rows-1 or j == 0 or j == columns-1:
      print("*", end="")
    else:
      print(" ", end="")
  print()

rows = 5

for i in range(rows):
    # Print leading spaces
    for j in range(rows - i - 1):
        print(" ", end="")
    # Print asterisks
    for k in range(2 * i + 1):
        print("*", end="")
    print()

for i in range(rows - 2, -1, -1):
    # Print leading spaces
    for j in range(rows - i - 1):
        print(" ", end="")
    # Print asterisks
    for k in range(2 * i + 1):
        print("*", end="")
    print()

for i in range(5):
    for j in range(5 - i - 1):
        print(" ", end="")
    for k in range(2*i +1):
        print("*", end="")
    print()

for i in range(5):
  print("*" * (i+1))

for i in range(5):
  for j in range(i+1):
    print("*" , end="")
  print()

for i in range(5):
  for j in range(5):
    print("*", end=" ")
  print()

a = [[1,2],[3,4]]
c = a[:]

c[0].append(99)
print(a)

a = [1,2,3]
b = a
c = a[:]

b.append(4)
c.append(5)

print(a)
print(b)
print(c)

numbers = [2,8,4,32,16]
max = numbers[0]
for i in range(len(numbers)):
  if numbers[i] > max:
    max = numbers[i]

print(max)

help()

help(range)