# -*- coding: utf-8 -*-
"""Week3_Session1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2VU70JQtQZ3yYEVnNwJ-Rn4_n-A3Ri7
"""



letter = input()
if letter.isalpha() :
  print("ALPHA")
  if letter.isupper() :
    print(letter.lower())
  else :
    print(letter.upper())
elif letter.isdigit() :
  print("Digit")

Char = input()
if Char.isalpha() :
  print("ALPHA")
  if Char.isupper() :
    print("Is Capital")
  else :
    print("Is Small")
elif Char.isdigit() :
  print("Digit")

C = input("Enter the Traffic Light Color: ")
if C == "R":
  print("Stop")
elif C == "Y":
  print("Get Ready")
elif C == "G":
  print("Go")
else :
  print("Invalid Color")

c = input("Enter the Traffic Light Color: ")
match c:
  case "R":
    print("Stop")
  case "Y":
    print("Get Ready")
  case "G":
    print("Go")
  case _:
    print("Invalid Color")

color = input("Enter a Clolor: ")
match color:
  case "Red"|"Green"|"Blue":
    print("Primary Color")
  case _:
    print("Other Color")

color = input("Enter a Clolor: ")
if color == "Red" or color == "Green" or color == "Blue":
  print("Primary Color")
else :
  print("Other Color")

color = input("Enter a Clolor: ")
if color in ["Red","Green","Blue"]:
  print("Primary Color")
else :
  print("Other Color")

color = input("Enter a Clolor: ")
ls = ["Red","Green","Blue"]
if color in ls:
  print("Primary Color")
else :
  print("Other Color")

color = input("Enter a Clolor: ")
ls = ["Red","Green","Blue"]
match color:
  case c if c in ls:
    print("Primary Color")
  case _:
    print("Other Color")

a = b = []
a = a + [1]
print(b)

s = "Python, Java, C++"
ls = s.split(", ")
print(ls)

ls1 = ["Apple", "Bannana"]
ls1.append("Orange")
print(ls1)

ls1.remove("Apple")
print(ls1)

scors = [50,10,90]
scors.sort()
print(scors)

s = input("Enter a string: ")
if s[0] == s[-1]:
  print("Match")
else:
  print("Not Match")

match s:
  case str if s[0] == s[-1]:
    print("Match")
  case _:
    print("Not Match")

ls = [2,4,8]

for i in ls:
  if i > i-1 :
    max = i
print(max)

if ls[0] > ls[1] and ls[0] > ls[2]:
  print(ls[0])

elif ls[1] > ls[0] and ls[1] > ls[2]:
  print(ls[1])

else :
  print(ls[2])


match ls:
  case [a,b,c] if a>b and a>c:
    print(a)
  case [a,b,c] if b>a and b>c:
    print(b)
  case [a,b,c] if c>a and c>b:
    print(c)