# -*- coding: utf-8 -*-
"""Week2_Session2_me.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDP1vldi7BUwCYulEyeYXF2JT5hDCe3w
"""

s = "Programming"
print(s[1:-1:2])

num = int(input("Enter a number: "))
if num % 2 == 0 and num % 3 == 0:
  print("The number is divisible by both 2 and 3")
elif num % 2 == 0:
  print("The number is divisible by 2 only")
elif num % 3 == 0:
  print("The number is divisible by 3 only")
else :
  print("The number is not divisible by 2 or 3")

user_name = input("Enter your User name: ")
age = int(input("Enter your age: "))

if user_name == "admin" and age >= 18 :
  print("Welcome Admin")
elif user_name != "admin" and age >= 18 :
  print("Welcome User")
else :
  print("You are too young to enter")

# Find the index of a char : repeated
s = "Ali Saad"
first_occurence = s.find("a")
print(first_occurence)
print(s.find("a",first_occurence+1))

text = "ababaBABa"
search = "aba"
text = text.lower()

count = 0
for i in range(len(text) - len(search) + 1):
    if text[i : i + len(search)] == search:
        count += 1

result = count
print(result)

s = "hello"
for i in range(len(s)):
  if s[i] == "l":
    print(i)